fix: module cannot be power on when status is off

diff --git a/cell_mgmt b/cell_mgmt
--- a/cell_mgmt
+++ b/cell_mgmt
@@ -1864,6 +1864,12 @@ get_op_func() {
 	local op_func=""
 
 
+	[ -z "${INTERFACE}" ] && \
+		[ "${arg1}" != "power_on" ] && \
+		[ "${arg1}" != "power_off" ] && \
+		[ "${arg1}" != "power_cycle" ] && \
+			>&2 echo "Error: Module not found." && exit 1
+
 	case "$arg1" in
 		# private options
 		post_start)
@@ -2164,9 +2170,7 @@ while getopts  "i:s:" flag; do
 	elif [ "${flag}" == "s" ]; then
 		SLOT=$OPTARG
 		INTERFACE=$(_cell_interface_by_slot ${SLOT})
-		[ -z "${INTERFACE}" ] && \
-			>&2 echo "Error: Module not found." && exit 1
-		_set_variables
+		[ ! -z "${INTERFACE}" ] && _set_variables
 	fi
 done
 
